all: encoder encoderM decoder decoderM keygen
	
encoder: 
	gcc otp_enc_d.c -o otp_enc_d
encoderM: 
	gcc otp_enc.c -o otp_enc
decoder:
	gcc otp_dec_d.c -o otp_dec_d
decoderM:
	gcc otp_dec.c -o otp_dec
keygen:
	gcc keygen.c -o keygen